---
name: test # this string appears on badge

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show environment
        run: |
          node --version
          npm --version

      - name: Install package
        run: npm ci

      - name: Test
        run: npm test
